# Generated by Django 5.0.4 on 2024-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='apply_to_email',
            field=models.EmailField(default='company@gmail.com', max_length=254),
        ),
    ]
