# Generated by Django 5.0.4 on 2024-08-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_apply_to_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='hr',
        ),
    ]
