# Generated by Django 5.0.4 on 2024-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='apply_to_email',
            field=models.EmailField(default='company@gmail.com', max_length=254),
        ),
    ]
