# Generated by Django 5.0.4 on 2024-08-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_jobapplication_apply_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
