# Generated by Django 5.0.4 on 2024-08-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applier_name',
            field=models.CharField(default='hemang', max_length=50),
        ),
    ]
