# Generated by Django 5.0.4 on 2024-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_jobapplication_applier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Vadodara', max_length=50),
        ),
    ]
